### ISSUE TITLE
Consider to add nRF Command Line Tools

### ISSUE THREAD

**Issue by stsdc** [charliebruce/nrf5-docker-build#2]
[nRF Command Line Tools](https://www.nordicsemi.com/Software-and-tools/Development-Tools/nRF-Command-Line-Tools/Download#infotabs)

**Comment by stsdc** [comment]
```
wget --no-check-certificate -qO cmd_tools https://www.nordicsemi.com/-/media/Software-and-other-downloads/Desktop-software/nRF-command-line-tools/sw/Versions-10-x-x/10-11-1/nRFCommandLineTools10111Linuxamd64tar.gz && \
    tar zxf cmd_tools
```
They now provide a deb package so it is only `apt install` routine.

**Comment by charliebruce** [comment]
Hi - thanks for the suggestion. Do you want this specifically for `nrfjprog`? If so, this is a bit of a pain, as you also have to map the JLink USB device in to the Docker container. Not sure how well this works, I haven't tested - will give it a go if you want though.

If you want to use `mergehex`, the same functionality can be achieved with `srec_cat` which is already installed in the Docker images. Eg:

```
srec_cat $(SOFTDEVICE) -intel $(BOOTLOADER) -intel $(APPLICATION) -intel -o complete-firmware.hex -intel -address-length=4
```

**Comment by stsdc** [comment]
If you want to be able to use the combined hex file with nRF Connect you should use Nordic's mergehex tool, that's why :c
I'm not going to use it with real device. Only to build on CI.

**Comment by charliebruce** [comment]
I believe that:
```srec_cat $(SOFTDEVICE) -intel $(BOOTLOADER) -intel $(APPLICATION) -intel -o complete-firmware.hex -intel -address-length=4```
should produce identical results to
```mergehex -m $(SOFTDEVICE) $(BOOTLOADER) $(APPLICATION) -o complete-firmware.hex```

The reason I used `srec_cat` instead of including `mergehex` was that Nordic's tool has a limitation of 3 hex files. Additionally, `srecord` has some more advanced outputs, including converting binary files to C arrays.

Have you tried using `srecord` and had issues with nRF Connect as a result? If so, would be happy to take a look.

**Comment by stsdc** [comment]
I'll check this out. Thanks.

**Comment by stsdc** [comment]
Hello, @charliebruce !
Please look at the discussion on https://github.com/OpenSource-EBike-firmware/TSDZ2_wireless/pull/22

**Comment by charliebruce** [comment]
We got this working without needing `mergehex` - no need to add this tool in the end.
